export const LOG_IN_USER = 'LOG_IN_USER';
export const LOAD_STATE = 'LOAD_STATE';
export const HANDLE_SORT_DIRECTION = 'HANDLE_SORT_DIRECTION';
export const HANDLE_CHANGE_FILTER = 'HANDLE_CHANGE_FILTER';
export const HANDLE_CHANGE_SEARCH = 'HANDLE_CHANGE_SEARCH';
export const HANDLE_IS_OPEN_SEARCH = 'HANDLE_IS_OPEN_SEARCH';
export const HANDLE_OPEN_INFO = 'HANDLE_OPEN_INFO';
export const HANDLE_CLOSE_INFO = 'HANDLE_CLOSE_INFO';
export const HANDLE_CHANGE_FILTER_AMOUNT_MIN =
  'HANDLE_CHANGE_FILTER_AMOUNT_MIN';
export const HANDLE_CHANGE_FILTER_AMOUNT_MAX =
  'HANDLE_CHANGE_FILTER_AMOUNT_MAX';
export const HANDLE_CHANGE_FILTER_STATUS = 'HANDLE_CHANGE_FILTER_STATUS';
export const HANDLE_CHANGE_FILTER_DATE_MIN = 'HANDLE_CHANGE_FILTER_DATE_MIN';
export const HANDLE_CHANGE_FILTER_DATE_MAX = 'HANDLE_CHANGE_FILTER_DATE_MAX';
export const HANDLE_IS_OPEN_NEW_PAYMENT = 'HANDLE_IS_OPEN_NEW_PAYMENT';
export const HANDLE_USER_EXIT = 'HANDLE_USER_EXIT';
